<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Room extends \App\Entity\Room implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
  'options' => NULL,
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
  'options' => NULL,
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {
        unset($this->options);

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }

    /**
     * 
     * @param string $name
     */
    public function __get($name)
    {
        if (\array_key_exists($name, self::$lazyPropertiesNames)) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__get', [$name]);
            return $this->$name;
        }

        trigger_error(sprintf('Undefined property: %s::$%s', __CLASS__, $name), E_USER_NOTICE);

    }

    /**
     * 
     * @param string $name
     * @param mixed  $value
     */
    public function __set($name, $value)
    {
        if (\array_key_exists($name, self::$lazyPropertiesNames)) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__set', [$name, $value]);

            $this->$name = $value;

            return;
        }

        $this->$name = $value;
    }

    /**
     * 
     * @param  string $name
     * @return boolean
     */
    public function __isset($name)
    {
        if (\array_key_exists($name, self::$lazyPropertiesNames)) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__isset', [$name]);

            return isset($this->$name);
        }

        return false;
    }

    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Room' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Room' . "\0" . 'nb_personnes', '' . "\0" . 'App\\Entity\\Room' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Room' . "\0" . 'type', '' . "\0" . 'App\\Entity\\Room' . "\0" . 'prix', '' . "\0" . 'App\\Entity\\Room' . "\0" . 'idHotel', 'options', '' . "\0" . 'App\\Entity\\Room' . "\0" . 'id2', '' . "\0" . 'App\\Entity\\Room' . "\0" . 'reservationHotels'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Room' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Room' . "\0" . 'nb_personnes', '' . "\0" . 'App\\Entity\\Room' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Room' . "\0" . 'type', '' . "\0" . 'App\\Entity\\Room' . "\0" . 'prix', '' . "\0" . 'App\\Entity\\Room' . "\0" . 'idHotel', '' . "\0" . 'App\\Entity\\Room' . "\0" . 'id2', '' . "\0" . 'App\\Entity\\Room' . "\0" . 'reservationHotels'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Room $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

            unset($this->options);
        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getId2(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId2', []);

        return parent::getId2();
    }

    /**
     * {@inheritDoc}
     */
    public function getNbPersonnes(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbPersonnes', []);

        return parent::getNbPersonnes();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbPersonnes(int $nb_personnes): \App\Entity\Room
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbPersonnes', [$nb_personnes]);

        return parent::setNbPersonnes($nb_personnes);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(string $description): \App\Entity\Room
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getType(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setType(string $type): \App\Entity\Room
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrix(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrix', []);

        return parent::getPrix();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrix(int $prix): \App\Entity\Room
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrix', [$prix]);

        return parent::setPrix($prix);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdHotel(): ?\App\Entity\hotel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdHotel', []);

        return parent::getIdHotel();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdHotel(?\App\Entity\Hotel $idHotel): \App\Entity\Room
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdHotel', [$idHotel]);

        return parent::setIdHotel($idHotel);
    }

    /**
     * {@inheritDoc}
     */
    public function getOptions(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOptions', []);

        return parent::getOptions();
    }

    /**
     * {@inheritDoc}
     */
    public function addOption(\App\Entity\Options $option): \App\Entity\Room
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOption', [$option]);

        return parent::addOption($option);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOption(\App\Entity\Options $option): \App\Entity\Room
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOption', [$option]);

        return parent::removeOption($option);
    }

    /**
     * {@inheritDoc}
     */
    public function getReservationHotels(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReservationHotels', []);

        return parent::getReservationHotels();
    }

    /**
     * {@inheritDoc}
     */
    public function addReservationHotel(\App\Entity\ReservationHotel $reservationHotel): \App\Entity\Room
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addReservationHotel', [$reservationHotel]);

        return parent::addReservationHotel($reservationHotel);
    }

    /**
     * {@inheritDoc}
     */
    public function removeReservationHotel(\App\Entity\ReservationHotel $reservationHotel): \App\Entity\Room
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeReservationHotel', [$reservationHotel]);

        return parent::removeReservationHotel($reservationHotel);
    }

}
