vich_uploader:
    db_driver: orm

    mappings:
       voyages:
           uri_prefix: /voyages
           upload_destination: '%kernel.project_dir%/public/voyages'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer


           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true

