<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5c6DGre\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5c6DGre/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5c6DGre.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5c6DGre\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container5c6DGre\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '5c6DGre',
    'container.build_id' => '2b53581c',
    'container.build_time' => 1616540287,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5c6DGre');
