<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQl8wkja\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQl8wkja/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQl8wkja.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQl8wkja\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerQl8wkja\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Ql8wkja',
    'container.build_id' => 'b44cc3a3',
    'container.build_time' => 1617187866,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQl8wkja');
