<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0X38AcV\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0X38AcV/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0X38AcV.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0X38AcV\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container0X38AcV\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '0X38AcV',
    'container.build_id' => '0f2e14cc',
    'container.build_time' => 1616948072,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0X38AcV');
